blank_issues_enabled: true
contact_links:
  - name: Usage questions
    url: https://github.com/pyronear/pyro-vision/discussions
    about: Ask questions and discuss with other Pyronear community members
